package uk.ac.brighton.jamss;

import java.awt.BorderLayout;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JSlider;

/**
 * 
 * @author Nick Walker
 * This class provides the GUI for the metronome
 */
public class MetronomePanel extends JPanel {
	
	private Metronome metronome = new Metronome();
	
	/**
	 * Create a frame and panel for the UI
	 */
	public static void main(String[] args) {
		JFrame f = new JFrame("Settings");
		final JPanel met = new MetronomePanel();
		met.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
		f.getContentPane().add(met, BorderLayout.CENTER);
		f.pack();
		f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		f.setLocationRelativeTo(null);
		f.setVisible(true);
		
	}
	
	/**
	 * Constructor
	 */
	public MetronomePanel(){
		initComponents();
		metronomeButton.requestFocus();
	}
	
	/**
	 * Sets the text for the start button
	 */
	private void setMetronomeButtonText(int beatsPerMinute) {
		metronomeButton.setText(Integer.toString(beatsPerMinute) + "bpm JAM!");
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		metronomeButton = new javax.swing.JToggleButton();
		scaleChooser = new javax.swing.JComboBox();
		rootChooser = new javax.swing.JComboBox();
		drumChooser = new javax.swing.JComboBox();
		leadChooser = new javax.swing.JComboBox();
		tempoChooser = new javax.swing.JSlider();

		setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));
		setLayout(new java.awt.GridBagLayout());

		metronomeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		metronomeButton.setText("72bpm JAM!");
		metronomeButton.setToolTipText("Start and stop the jam session");
		metronomeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				metronomeButtonActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
		add(metronomeButton, gridBagConstraints);

		scaleChooser.setModel(new javax.swing.DefaultComboBoxModel(ScaleChoice.getSChoice()));
		scaleChooser.setToolTipText("Select the scale to use");
		scaleChooser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				soundChooserActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		add(scaleChooser, gridBagConstraints);

		//FOR ROOT NOTE CHOICE
		rootChooser.setModel(new javax.swing.DefaultComboBoxModel(RootChoice.getRChoice()));
		rootChooser.setToolTipText("Select the root to use");
		rootChooser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rootChooserActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		add(rootChooser, gridBagConstraints);

		//FOR DRUMS CHOICE
		drumChooser.setModel(new javax.swing.DefaultComboBoxModel(DrumChoice.getDChoice()));
		drumChooser.setToolTipText("Select the drums to use");
		drumChooser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				drumChooserActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
		add(drumChooser, gridBagConstraints);

		//FOR LEAD
		leadChooser.setModel(new javax.swing.DefaultComboBoxModel(LeadSound.getSounds()));
		leadChooser.setToolTipText("Select the sound to use");
		leadChooser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				leadChooserActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
		add(leadChooser, gridBagConstraints);

		//FOR TEMPO
		tempoChooser.setMaximum(160);
		tempoChooser.setMinimum(40);
		tempoChooser.setValue(72);
		tempoChooser.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				tempoChooserStateChanged(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
		add(tempoChooser, gridBagConstraints);
	}// </editor-fold>//GEN-END:initComponents

	private void metronomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metronomeButtonActionPerformed

		if (metronomeButton.isSelected()) {
			metronome.startThread();
		} else {
			metronome.drums.stop();
			metronome.drumsOn = false;
			metronome.stop();
		}

	}//GEN-LAST:event_metronomeButtonActionPerformed

	private void soundChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundChooserActionPerformed
		metronome.setScaleFromChoice((((ScaleChoice)scaleChooser.getSelectedItem()).getName()));
	}//GEN-LAST:event_soundChooserActionPerformed

	private void rootChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundChooserActionPerformed
		metronome.setRootFromChoice((((RootChoice)rootChooser.getSelectedItem()).getName()));
	}//GEN-LAST:event_soundChooserActionPerformed

	private void drumChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundChooserActionPerformed
		metronome.setDrumFromChoice((((DrumChoice)drumChooser.getSelectedItem()).getName()));
	}//GEN-LAST:event_soundChooserActionPerformed

	private void leadChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundChooserActionPerformed
		metronome.setLeadFromChoice(((LeadSound)leadChooser.getSelectedItem()).getMidiNote());
	}//GEN-LAST:event_soundChooserActionPerformed

	private void tempoChooserStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tempoChooserStateChanged
		final int tempo = tempoChooser.getValue();
		if (((JSlider) evt.getSource()).getValueIsAdjusting()) {
			if (metronome.drumsOn){
				metronome.drums.player.stop();
				metronome.drumsOn = false;
				metronome.stop();
			}
			setMetronomeButtonText(tempo);
		} else {
			metronome.processTempoChange(tempo);
			if (metronomeButton.isSelected()) {
				metronome.startThread();
			}
		}
	}//GEN-LAST:event_tempoChooserStateChanged

	public Metronome getMetronome() {
		return metronome;
	}

	public void setMetronome(Metronome metronome) {
		this.metronome = metronome;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JToggleButton metronomeButton;
	private javax.swing.JComboBox scaleChooser;
	private javax.swing.JComboBox rootChooser;
	private javax.swing.JComboBox drumChooser;
	private javax.swing.JComboBox leadChooser;
	private javax.swing.JSlider tempoChooser;
	// End of variables declaration//GEN-END:variables

}
